# Docker Compose file for LiteLLM with PostgreSQL and Adminer
name: litellm-docker

services:

  # PostgreSQL database
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres    
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      default:
        ipv4_address: 172.100.0.2
 
  # PgAdmin4 for PostgreSQL management
  pgadmin4:
    depends_on:
      - postgres
    image: dpage/pgadmin4:9.3.0
    ports:
      - 54321:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin4.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin4:/var/lib/pgadmin
    networks:
      default:
        ipv4_address: 172.100.0.3

  # LiteLLM proxy server for AI model serving
  lite-llm:
    depends_on:
      - postgres
    image: ghcr.io/berriai/litellm:main-latest
    networks:
      default:
        ipv4_address: 172.100.0.4
    ports:
      - 4000:4000
    environment:
      LITELLM_MASTER_KEY: sk-1234
      LITELLM_SALT_KEY: sk-XXXXXXXX
      DATABASE_URL: postgres://postgres:postgres@172.100.0.2:5432/litellm
      PORT: 4000
      STORE_MODEL_IN_DB: True
      UI_USERNAME: admin
      UI_PASSWORD: LiteLLM

  # Ollama for model serving
  ollama:
    restart: always
    image: ollama/ollama
    ports:
      - 11434:11434
    networks:
      default:
        ipv4_address: 172.100.0.5
    environment:
      OLLAMA_HOST: 0.0.0.0
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]      

  # n8n for workflow automation
  n8n:
    depends_on:
      - postgres
    image: n8nio/n8n
    ports:
      - 5678:5678
    networks:
      default:
        ipv4_address: 172.100.0.6      
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_HOST: 172.100.0.2
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_PASSWORD: postgres
    volumes:
      - n8n_data:/home/node/.n8n

  # Docling for document processing
  docling:
    image: quay.io/docling-project/docling-serve
    ports:
      - 5001:5001
    environment:
      DOCLING_SERVE_ENABLE_UI: true
    networks:
      default:
        ipv4_address: 172.100.0.7

  # ChromaDB for vector database
  chromadb:
    image: chromadb/chroma:1.0.9.dev38
    ports:
      - 8000:8000
    environment:
      IS_PERSISTENT: true
      ANONYMIZED_TELEMETRY: true
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      default:
        ipv4_address: 172.100.0.8

  # AnythingLLM for Workspaces and LLM RAG with own documents
  anything-llm:
    image: mintplexlabs/anythingllm
    ports:
      - 3001:3001
    environment:
      STORAGE_DIR: /app/server/storage
      STORAGE_LOCATION: /app/server/storage
      EMBEDDING_ENGINE: ollama
      EMBEDDING_BASE_PATH: http://host.docker.internal:11434
      EMBEDDING_MODEL_PREF: nomic-embed-text:latest
      EMBEDDING_MODEL_MAX_CHUNK_LENGTH: 8192
      LLM_PROVIDER: ollama
      OLLAMA_BASE_PATH: http://host.docker.internal:11434
      OLLAMA_MODEL_PREF: phi4:14b
      OLLAMA_MODEL_TOKEN_LIMIT: 16184
      VECTOR_DB : chroma
      CHROMA_ENDPOINT: http://172.100.0.8:8000
      CHROMA_API_HEADER: x-chroma-token
      CHROMA_API_KEY: x-chroma-token
    command: --cap-add SYS_ADMIN
    volumes:
      - anything_llm_storage:/app/server/storage
    networks:
      default:
        ipv4_address: 172.100.0.9

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/24

volumes:
  pgdata:
  pgadmin4:
  ollama:
  n8n_data:
  chroma_data:
  anything_llm_storage:
      driver: local
      driver_opts:
        type: none
        device: E:/anythingllm-storage
        o: bind
  open_webui_data_uploads:
    driver: local
    driver_opts:
      type: none
      device: E:/ollama/data
      o: bind