# Docker Compose file for LiteLLM with PostgreSQL and Adminer
name: litellm-docker

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres    
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      default:
        ipv4_address: 172.100.0.2      
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 54321:8080
    networks:
      default:
        ipv4_address: 172.100.0.3

  lite-llm:
    image: ghcr.io/berriai/litellm:main-latest
    restart: always
    networks:
      default:
        ipv4_address: 172.100.0.4
    depends_on:
      - postgres
    ports:
      - 4000:4000
    environment:
      LITELLM_MASTER_KEY: sk-1234
      LITELLM_SALT_KEY: sk-XXXXXXXX
      DATABASE_URL: postgres://postgres:postgres@172.100.0.2:5432/litellm
      PORT: 4000
      STORE_MODEL_IN_DB: True
      UI_USERNAME: admin
      UI_PASSWORD: LiteLLM

  open-webui-with-ollama:
    depends_on:
      - lite-llm  
    image: ghcr.io/open-webui/open-webui:ollama
    restart: always
    ports:
      - 3000:8080
      - 11434:11434
    networks:
      default:
        ipv4_address: 172.100.0.5
    environment:
      HF_HUB_OFFLINE: 1
      OLLAMA_HOST: 0.0.0.0
      STORE_MODEL_IN_DB: true
      STORE_PROMPTS_IN_SPEND_LOGS: true
    volumes:
      - ollama:/root/.ollama

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/24

volumes:
  pgdata:
  ollama: